### ISSUE TITLE
Bug Report #1

### ISSUE THREAD

**Issue by Unscheduled** [funkemunky/Fiona-Issues#12]
Fiona Version: Fiona v2.0-BETA~2
 ProtocolLib Version: 3.7.0
 Plugin List: https://gyazo.com/46480775f84d78c8c495accd98044d94
 Description: Everytime a player move's he set's of a number of log's until the player get's banned.
 Screenshot/Video Media: https://gyazo.com/00b464c83a3e3a1c8ee4a188def75e93

**Comment by funkemunky** [comment]
Thanks for the report, but I need to know if it’s still an issue on the latest version. Make another Issue if it is.
